### ISSUE TITLE
kitodo-demo differ to demo installation: Inhaltsverzeichnis / Table of Content

### ISSUE THREAD

**Issue by BFallert** [kitodo/kitodo-demo#5]
The demo installation (at https://presentation-demo.kitodo.org/) differ from the kitodo/kitodo-demo. 

### In the demo installation:
    <div id="c6" class="csc-default"><div class="tx-dlf-toc">
        <div class="detail-view-itemcontents">
            <div class="dropdown-menu">
                <input type="checkbox" id="checkbox-menu1">
                <label for="checkbox-menu1">Inhaltsverzeichnis</label>
                <ul>
                    <li class="tx-dlf-toc-act tx-dlf-toc-ifsub">
                        ...
                    </li>
                </ul>
            </div>
        </div>
    </div>

### In kitodo/kitodo-demo:
    <a id="cXXX"></a>
    <div class="tx-dlf-TableOfContents">
        <ul>
            <li class="tx-dlf-toc-act tx-dlf-toc-ifsub">
            ...
            </li>
        </ul>
    </div>

Probably the template `Resources/Private/Template/DetailTemplate.html` is different?

**Comment by BFallert** [comment]
I used the wrong Template!

I used the template from 
- `kitodo-presentation/Resources/Private/Template/TableOfContents.tmpl`

but i have to use
* `presentation_package/Resources/Public/PluginTemplates/toc.tmpl`

I can not use both templates directly, I have to copy them to a directory in fileadmin first. If I insert the code directly within the template `Resources/Private/Template/DetailTemplate.html`, the opening and closing of the table of contents will not work.

**Comment by BFallert** [comment]
Is this the right way that i have to copy the template files from `presentation_package/Resources/Public/PluginTemplates/` into the fileadmin directory?

**Comment by BFallert** [comment]
@chrizzor: Is this the right way that i have to copy the template files from `presentation_package/Resources/Public/PluginTemplates/` into the fileadmin directory?

**Comment by chrizzor** [comment]
I would say that there is no "right way". 
You can copy them to fileadmin or upload each file directly.
As long as they are available in the backend, it is the right way.

**Comment by sebastian-meyer** [comment]
@BFallert: Yes, it is the right way to maintain your own copies of the template files outside the extension directory. That way you can update the extension without overwriting your custom templates.
